name: pushimg

on: [push]

jobs:

push-dev-image:

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v2

- name: Login to GitHub Container Registry

uses: docker/login-action@v1

with:

registry: ghcr.io

username: ${{ github.actor }}

password: ${{ secrets.GITHUB_TOKEN }}

- name: Build the dev Docker image

run: |
       docker build . --tag ghcr.io/tushar-mohan/dev:latest
       docker push ghcr.io/tushar-mohan/dev:latest
